### ISSUE TITLE
getquota in imaputils has an unbound variable

### ISSUE THREAD

**Issue by cl-parsons** [modoboa/modoboa-webmail#224]
This exception is raised when I try to access the webmail.

```
Internal Server Error: /webmail/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/modoboa_webmail/lib/imaputils.py", line 686, in getquota

    data = self._cmd("GETQUOTAROOT", self._encode_mbox_name(mailbox),
  File "/usr/local/lib/python3.9/site-packages/modoboa_webmail/lib/imaputils.py", line 415, in _encode_
mbox_name
    return b'"' + folder.encode("imap4-utf-7") + b'"'
LookupError: unknown encoding: imap4-utf-7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_respons
e
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_respons
e
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped
_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/modoboa/admin/lib.py", line 40, in wrapped_f
    return f(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/modoboa_webmail/views.py", line 662, in index
    imapc.getquota(curmbox)
  File "/usr/local/lib/python3.9/site-packages/modoboa_webmail/lib/imaputils.py", line 691, in getquota

    if data is None:
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by psztoch** [comment]
It is related to: #227
