### ISSUE TITLE
Server reports error (on opening message ?)

### ISSUE THREAD

**Issue by yeeno** [modoboa/modoboa-webmail#28]
Internal Server Error: /webmail/getmailcontent
Traceback (most recent call last):
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, _callback_args, *_callback_kwargs)
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
   return func(_args, *_kwargs)
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
   return view_func(request, _args, *_kwargs)
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/modoboa_admin/lib.py", line 30, in wrapped_f
   return f(request, _args, *_kwargs)
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/modoboa_webmail/views.py", line 491, in getmailcontent
   links=int(request.GET["links"])
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py", line 44, in __init__
   headers = self.msg['BODY[HEADER.FIELDS (%s)]' % self.headers_as_text]
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py", line 82, in msg
   headers=self.headers_as_list
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py", line 757, in fetchmail
   "(BODYSTRUCTURE %s[HEADER.FIELDS (%s)])" % (bcmd, " ".join(headers))
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py", line 200, in _cmd
   return parse_fetch_response(data)
 File "/srv/pythonbrew/venvs/Python-2.7.10/mailadmin/lib/python2.7/site-packages/modoboa_webmail/lib/fetch_parser.py", line 140, in parse_fetch_response
   content += data[cpt]
TypeError: can only concatenate tuple (not "NoneType") to tuple

Request repr(): 
<WSGIRequest
path:/webmail/getmailcontent,
GET:<QueryDict: {u'mailid': [u'6036'], u'mbox': [u'Einladung zu Infoveranstaltung schicken'], u'links': [u'0']}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': '4oCEFlehOQXMVFfwAT55Sp5BjlkBkwWC',
'sessionid': 'a4748q7qjzlaz83hu2tsbuhtzl5hgxjv'},
META:{u'CSRF_COOKIE': u'4oCEFlehOQXMVFfwAT55Sp5BjlkBkwWC',
'DOCUMENT_ROOT': '/var/www/mailadmin/',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_ACCEPT_LANGUAGE': 'de-de',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'csrftoken=4oCEFlehOQXMVFfwAT55Sp5BjlkBkwWC; sessionid=a4748q7qjzlaz83hu2tsbuhtzl5hgxjv',
'HTTP_HOST': 'domain.com',
'HTTP_REFERER': 'http://domain.com/webmail/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3',
'PATH_INFO': u'/webmail/getmailcontent',
'PATH_TRANSLATED': '/var/www/mailadmin/mailadmin/wsgi.py/webmail/getmailcontent',
'QUERY_STRING': 'mbox=Einladung%20zu%20Infoveranstaltung%20schicken&mailid=6036&links=0',
'REMOTE_ADDR': '111.222.333.444',
'REMOTE_PORT': '49472',
'REQUEST_METHOD': 'GET',
'REQUEST_URI': '/webmail/getmailcontent?mbox=Einladung%20zu%20Infoveranstaltung%20schicken&mailid=6036&links=0',
'SCRIPT_FILENAME': '/var/www/mailadmin/mailadmin/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '78.46.64.234',
'SERVER_ADMIN': 'sysadmin@domain.com',
'SERVER_NAME': 'domain.com',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.2.16',
'mod_wsgi.application_group': 'domain.com|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'domain.com',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f20bca9c4f0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f20bcbb0300>,
'wsgi.input': <mod_wsgi.Input object at 0x7f20bca712f0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 1)}>

**Comment by tonioo** [comment]
Hi, do you still have the message that was causing this issue ?

**Comment by yeeno** [comment]
Yes, because I didn’t make any update since then. Is the error fixed?

Viele Grüße  - Michael

Michael Adams :: Bismarckstr. 53 :: D-47799 Krefeld
michael@adamsmail.de :: michaeladams.de
Telefon +49 2151 74767062 :: mobil +49 172 2778835 :: Fax +49 2151 74767069

**Comment by tonioo** [comment]
Not yet but it would be easier to fix with the message structure... What kind of message is it ? (attachments, HTML, text, etc.)

**Comment by yeeno** [comment]
I’m personally not using the webmail client, I only get the error messages. I even don’t know how often the users work with it and which emails cause the problem. Sorry, I can’t help you here.
