### ISSUE TITLE
Missing file 396_image002.jpg@01D0C534.286E1A60

### ISSUE THREAD

**Issue by adam-codeberg** [modoboa/modoboa-webmail#29]
Get the following error when trying to view some emails via webmail

Not sure why its looking for a file at that location

```python
Traceback (most recent call last):
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/modoboa_admin/lib.py", line 30, in wrapped_f
    return f(request, *args, **kwargs)
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/modoboa_webmail/views.py", line 496, in getmailcontent
    "mailbody": email.body if email.body else ""
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py", line 129, in body
    self._fetch_inlines()
  File "/root/.pyenv/versions/modoboa-py2-7-6/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py", line 185, in _fetch_inlines
    with open(path, "wb") as fpo:
IOError: [Errno 2] No such file or directory: u'./media/modoboa_webmail/396_image002.jpg@01D0C534.286E1A60'
```

**Comment by tonioo** [comment]
Yes, you need to manually create the media/modoboa_webmail folder to fix it.

**Comment by adam-codeberg** [comment]
Any idea what the base path is at . ?

**Comment by tonioo** [comment]
Check the folder where you deployed modoboa. You should find a sitestatic folder inside, use it as the base path.

**Comment by adam-codeberg** [comment]
Yes thats the one.

This issue is caused when a user embeds an image in the email. 
Its trying to retrieve the email from that filepath.

Trying to work out if its an issue with the webproxy, uwsgi or modoboa.

**Comment by adam-codeberg** [comment]
Quick followup.

Created a folder under;
$ <modoboa's directory>/modoboa_webmail/
Gave it the appropriate file permissions and the problem was solved.

Had to repeat a similar process for file attachments as they require the following folder;
$ <modoboa's directory>/webmail/attachments/
