### ISSUE TITLE
Maximum attachment size - Don't apply change after value update.

### ISSUE THREAD

**Issue by themsay** [modoboa/modoboa-webmail#61]
version==1.6.3

I get this error message on my Thunderbird on attachment size of 26.0 MB "The size of the message you are trying to send exceeds the global size limit (11534336 bytes) of the server. The message was not sent; reduce the message size and try again."

I tried to update Parameters > Webmail > Maximum attachment size: default 2048 to higher values, but it doesn't apply my change on save. I try by adding (MB) to the value e.g 4096MB but still returned 2048 as I reload the page.

I decided to upgrade to modoboa==1.7.1, as I ran "python manage.py migrate" then I encounter an error:
<code>
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_radicale/models.py", line 15, in <module>
    from modoboa.lib import parameters
ImportError: cannot import name parameters
</code>

I downgrade to 1.6.3 for now.

**Comment by tonioo** [comment]
The message size limit is defined in the `/etc/postfix/main.cf` file and Modoboa does not modify it so you have to do it manually. The setting you're trying to change only concerns the web interface (max. upload size while you're composing a message).

About your trace, have you tried to upgrade modoboa?

**Comment by themsay** [comment]
Thanks you for the info on message size limit.

Have you tried to upgrade Modoboa? Yes

I followed the steps below:
<code>cd /srv/modoboa/ && . env/bin/activate</code>
<code>pip install modoboa==1.7.1</code>
<code>cd instance/</code>
<code>python manage.py migrate</code> - then got an error here.

**Comment by tonioo** [comment]
Ok but you forgot to upgrade extensions as mentioned in the upgrade procedure.

**Comment by themsay** [comment]
@tonioo your correct.

I use http://modoboa.readthedocs.io/en/latest/upgrade.html#extensions procedure on 1.7.0 section.
My upgrade from 1.6.3 to 1.7.1 is successful.

Thanks!

**Comment by themsay** [comment]
@tonioo your correct.

I use http://modoboa.readthedocs.io/en/latest/upgrade.html#extensions procedure on 1.7.0 section.
My upgrade from 1.6.3 to 1.7.1 is successful.

Thanks!
